import { StrictMode } from 'react';
import { BrowserRouter } from 'react-router-dom';
import { HelmetProvider } from 'react-helmet-async';
import * as ReactDOM from 'react-dom/client';
import App from './app/app';
import { ToastProvider } from './app/components/Toast';

const basename = import.meta.env.BASE_URL.replace(/\/$/, '') || '/';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement,
);

root.render(
  <StrictMode>
    <HelmetProvider>
      <ToastProvider>
        <BrowserRouter basename={basename}>
          <App />
        </BrowserRouter>
      </ToastProvider>
    </HelmetProvider>
  </StrictMode>,
);

// Register PWA service worker (generated by vite-plugin-pwa)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register(
      `${import.meta.env.BASE_URL}sw.js`,
    ).catch((err) => {
      console.warn('SW registration failed:', err);
    });
  });
}
